name: Deploy to WP Engine

on:
  push:
    branches: [main, develop, staging]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      THEME_DIR: wp-content/themes/rmit-learning-lab
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.THEME_DIR }}/package-lock.json

      - name: Install deps (theme)
        working-directory: ${{ env.THEME_DIR }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          npm i -D sass@^1.77
          npx sass --version

      - name: Sanity check vendor/rfs in theme
        run: |
          test -f "${THEME_DIR}/sass/bootstrap5/vendor/_rfs.scss" || { echo "Missing ${THEME_DIR}/sass/bootstrap5/vendor/_rfs.scss"; exit 65; }

      - name: Build CSS (theme, no external bootstrap)
        working-directory: ${{ env.THEME_DIR }}
        run: |
          mkdir -p css-output
          npx sass \
            --load-path=sass \
            --load-path=sass/bootstrap5 \
            sass/main.scss css-output/bundle.css \
            --style=compressed --source-map

      - name: Select WP Engine env
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            echo "WPE_ENV=${{ secrets.WPE_ENV_PRD }}" >> $GITHUB_ENV
          elif [ "$BRANCH" = "develop" ]; then
            echo "WPE_ENV=${{ secrets.WPE_ENV_DEV }}" >> $GITHUB_ENV
          elif [ "$BRANCH" = "staging" ]; then
            echo "WPE_ENV=${{ secrets.WPE_ENV_STG }}" >> $GITHUB_ENV
          else
            echo "Unsupported branch: $BRANCH"; exit 1
          fi

      - name: Deploy theme to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ env.WPE_ENV }}
          SRC_PATH: '${{ env.THEME_DIR }}/'
          REMOTE_PATH: '/${{ env.THEME_DIR }}/'
          CACHE_CLEAR: true
